openapi: 3.1.0

info:
  version: 2025.03.04.1
  title: INCI Beauty Pro API
  description: |
    This documentation is only available in English.

    # Authentication
    Each call to the API must include an HMAC parameter.<br>
    To generate the HMAC, you will need the following information:
    - Access Key ID
    - Secret Key

    You can find this information on the API's "Credentials" page.

    ## How to generate the HMAC?

    Get the path from the URL you want to call by removing the host. For example :

    **URL :**<br>
    `https://api.incibeauty.com/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]`

    **Path:**<br>
    `/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]`

    **Encoding:**<br>
    The parameters used for HMAC generation must be encoded according to RFC 1738.  
    Example: ?cursorMark=AoRRnhoIPoI0QQgAAAAAL2luZ3JlZGllbnQtNTY1Mw<b>==</b>  
    Should be: ?cursorMark=AoRRnhoIPoI0QQgAAAAAL2luZ3JlZGllbnQtNTY1Mw<b>%3D%3D</b>

    **Generating HMAC:**<br>

    **PHP**
    ```php
    $secretKey = "[YOUR_SECRET_KEY]";
    $path = "/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]";
    $hmac = hash_hmac("sha256", $path, $secretKey);
    ```

    <br>

    **Python3**
    ```python
    import hmac
    import hashlib

    secretKey = "[YOUR_SECRET_KEY]"
    path = "/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]"
    hmac = hmac.new(bytes(secretKey, "UTF-8"), path.encode("UTF-8"), hashlib.sha256).hexdigest()
    ```

    <br>

    **Ruby**
    ```ruby
    require 'openssl'

    secretKey = "[YOUR_SECRET_KEY]"
    path = "/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]"
    hmac = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new("sha256"), secretKey, path)
    ```

    <br>

    **Javascript (Node.js)**
    ```javascript
    const crypto = require("crypto");

    let secretKey = "[YOUR_SECRET_KEY]";
    let path = "/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]";
    let hmac = crypto.createHmac("sha256", secretKey).update(path).digest("hex");
    ```

    <br>

    **Go**
    ```go
    import (
      "crypto/hmac"
      "crypto/sha256"
      "encoding/hex"
    )

    secretKey := []byte("[YOUR_SECRET_KEY]")
    path := "/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]"
    hash := hmac.New(sha256.New, secretKey)
    hash.Write([]byte(path))
    hmac := hex.EncodeToString(hash.Sum(nil))
    ```

    ## How to use the HMAC ?

    Add the generated HMAC to the end of the URL you want to call: `&hmac=[HMAC]`
    
    **Final URL :**<br>
    `https://api.incibeauty.com/product/composition/4020829010567?accessKeyId=[YOUR_ACCESS_KEY]&hmac=[HMAC]`

    ## Postman Pre-request Script

    If you are using Postman for development purposes, you can generate and add the HMAC for each of your requests using the following Pre-request Script (to be configured at a collection level):

    ```javascript
    pm.request.removeQueryParams("hmac")
    pm.request.removeQueryParams("accessKeyId")
    pm.request.addQueryParams("accessKeyId={{accessKeyId}}")
    pm.request.addQueryParams(
        `hmac=${CryptoJS.HmacSHA256(
            pm.variables.replaceIn(pm.request.url.getPathWithQuery()),
            pm.variables.get("apiSecretKey")
          )
          .toString(CryptoJS.digest)}`
    )
    ```
    
    <br>

    Next, add these variables in a Postman environment:
    VARIABLE | TYPE | INITIAL VALUE
    ---------|------|--------------
    accessKeyId | default | Your Access Key ID
    apiSecretKey | secret | Your API Secret Key

    Make sure you have correctly configured the roles of your environments if you want to limit access to the `apiSecretKey` variable.

tags:
  - name: Ingredients
    description: |
      API which concerns cosmetic ingredients.<br>
      Subscription to the "Access to the Ingredients API" option is required in order to use these APIs.
  - name: Predictions
    description: |
      API that concerns the rate prediction and lets you manage your simulations.<br>
      These APIs are not yet integrated into the professional subscription offer. Contact us if you are interested.
  - name: Products
    description: |
      API that concerns the products of the application.<br>
      Subscription to the "Access to the Products API" option is required in order to use these APIs.
  - name: Ingredient_Object
    x-displayName: Ingredient
    description: |
      Properties that describe an ingredients.
      <SchemaDefinition schemaRef="#/components/schemas/Ingredient" />
  - name: IngredientFamily_Object
    x-displayName: Ingredient Family
    description: |
      Properties that describe a family of ingredients.
      <SchemaDefinition schemaRef="#/components/schemas/IngredientFamily" />
  - name: Offer_Object
    x-displayName: Offer
    description: |
      Properties that describe a sale offer.
      <SchemaDefinition schemaRef="#/components/schemas/Offer" />
  - name: Product_Object
    x-displayName: Product
    description: |
      Properties that describe a product.
      <SchemaDefinition schemaRef="#/components/schemas/Product" />

x-tagGroups:
  - name: API
    tags:
      - Ingredients
      - Predictions
      - Products
  - name: Objects
    tags:
      - Ingredient_Object
      - Offer_Object
      - Product_Object

servers:
- url: https://api.incibeauty.com/

paths:
  #--------------------------------------------------------------------------
  # Products
  #--------------------------------------------------------------------------
  "/product/price/{EAN}":
    get:
      tags: ["Products"]
      summary: Offers
      description: |
        Gets a list of sales offers for a product.
      parameters:
        - in: path
          name: EAN
          required: true
          schema:
            type: string
          description: An EAN code.
          example: 3522930003618
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Invalid EAN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
        '500':
          $ref: '#/components/responses/InternalError'

  "/product/composition/{EAN}/{Locale}":
    get:
      tags: ["Products"]
      summary: Composition
      description: |
        Allows you to obtain information about a product (brand, category, etc.) and its complete INCI composition.<br>
        A product can have more than one composition. For example gift sets, hair colouring, etc.
      parameters:
        - in: path
          name: EAN
          required: true
          schema:
            type: string
          description: An EAN code.
          example: 3522930003618
        - in: path
          name: Locale
          required: true
          schema:
            type: string
            enum:
              - fr_FR
              - es_ES
              - en_GB
              - it_IT
              - de_DE
              - pl_PL
              - sr_RS
              - hr_HR
              - pt_PT
              - bg_BG
              - nl_NL
              - hu_HU
              - ja_JP
              - ko_KR
              - ar_MA
              - he_IL
              - tr_TR
              - ro_RO
              - sk_SK
              - cs_CZ
          description: Data language.
          example: en_GB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Invalid EAN or Product not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
        '500':
          $ref: '#/components/responses/InternalError'
  

  #--------------------------------------------------------------------------
  # Ingredients
  #--------------------------------------------------------------------------
  "/ingredient/search/{KEYWORD}":
    get:
      tags: ["Ingredients"]
      summary: Search
      description: |
        Allows you to search for ingredients based on keywords.<br>
        You will need our internal ingredient identifiers to obtain their information.
      parameters:
        - in: path
          name: KEYWORD
          required: true
          schema:
            type: string
          description: Part of the name of the searched ingredients. Must be URL encoded.
          example: butyl%20methyl
        - in: query
          name: cursorMark
          schema:
            type: string
            default: "*"
          description: |
            Identifier to pass to the next request in order to obtain the results of the next page.<br>
            In the response, if the cursorMark is absent or identical to the cursorMark sent, there are no more results.<br>
            The value `*` corresponds to page 1.<br>
            If the parameter is omitted, page 1 will be returned by default.
          example: AoRDCECEQvYIAAAAADBpbmdyZWRpZW50LTIxMzkz
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    description: Search results.
                    items:
                      type: object
                      properties:
                        identifier:
                          type: string
                          description: Internal identifier.
                          example: "10584"
                        inci_name:
                          type: string
                          description: Ingredient name as listed in the INCI nomenclature.
                          example: BUTYLPHENYL METHYLPROPIONAL
                      required:
                        - identifier
                        - inci_name
                  cursorMark:
                    type: string
                    description: |
                      Identifier to pass to the next request in order to obtain the results of the next page.<br>
                      If the cursorMark is absent or identical to the cursorMark sent, there are no more results.
                    example: AoRDCECEQvYIAAAAADBpbmdyZWRpZW50LTIxMzkz
                required:
                  - docs
                  - cursorMark
                example:
                  docs:
                    - identifier: "10584"
                      inci_name: BUTYLPHENYL METHYLPROPIONAL
                    - identifier: "19813"
                      inci_name: METHYL DI-T-BUTYL HYDROXYHYDROCINNAMATE
                  cursorMark: AoRDCECEQvYIAAAAADBpbmdyZWRpZW50LTIxMzkz
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
  
  "/ingredient/{ID}":
    get:
      tags: ["Ingredients"]
      summary: Information
      description: |
        Provides information about an ingredient.
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
          description: Internal identifier retrieved via [search](#tag/Ingredients/paths/~1ingredient~1search~1%7BKEYWORD%7D/get).
          example: "9576"
        - in: query
          name: locale
          required: true
          schema:
            type: string
            enum:
              - fr_FR
              - es_ES
              - en_GB
              - it_IT
              - de_DE
              - pl_PL
              - sr_RS
              - hr_HR
              - pt_PT
              - bg_BG
              - nl_NL
              - hu_HU
              - ja_JP
              - ko_KR
              - ar_MA
              - he_IL
              - tr_TR
              - ro_RO
              - sk_SK
              - cs_CZ
          description: Data language.
          example: en_GB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

security:
  - AccessKeyID: []
    HMAC: []

components:
  securitySchemes:
    AccessKeyID:
      type: apiKey
      in: query
      name: accessKeyId
      description: Found on the API's "Credentials" page.
    HMAC:
      type: apiKey
      in: query
      name: hmac
      description: See [Authentication](#section/Authentication)
  
  responses:
    Unauthorized:
      description: Authentication error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultErrorResponse'
    
    InternalError:
      description: Internal Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DefaultErrorResponse'
  
  schemas:
    DefaultResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          example: success
        code:
          type: integer
          description: |
            [Voir les codes de retour possibles](#section/Reponse)
          example: 200
        message:
          type: string
          description: Un message en cas d'erreur.
      required:
        - status
        - code
    
    DefaultErrorResponse:
      oneOf:
        - type: object
          title: Simple error message
          properties:
            error:
              type: string
              description: Error message
              example: The signature is incorrect.
        - type: object
          title: Error message with status code.
          properties:
            error:
              type: object
              properties:
                message:
                  type: string
                  description: Error message
                  example: Invalid EAN.
                status_code:
                  type: number
                  format: int32
                  description: HTTP status code
                  example: 404
    
    Offer:
      type: object
      description: Properties that describe a sale offer.
      properties:
        id:
          type: string
          description: Internal identifier.
        eans:
          type: string
          description: EAN code of the product.
          example: "3522930003618"
        url:
          type: string
          format: uri
          description: URL to the sale offer proposed by the merchant.
        price:
          type: number
          format: float
          description: Sale offer price.
          example: 7.9
        currency:
          type: string
          description: Currency in which the sale offer is offered.
          example: EUR
        title:
          type: string
          description: Description of the offer provided by the merchant.
          example: Caudalie Vinotherapist Crème Réparatrice Mains et Ongles 75ml
        store:
          type: string
          description: Merchant name.
          example: Atida | Santediscount
        store_id:
          type: number
          format: int32
          description: Merchant ID.
          example: 3973
        store_logo:
          type: string
          format: uri
          description: URL to the merchant's logo.
          example: https://www.touslesprix.com/b_part/3973.gif
        languages:
          type: array
          description: Languages in which the merchant's site is available.
          items:
            type: string
          example:
            - fr
      required:
        - id
        - eans
        - url
        - price
        - currency
        - title
        - store
        - store_id
        - store_logo
    
    Product:
      type: object
      description: Properties that describe a product.
      properties:
        id:
          type: number
          format: int32
          description: Internal identifier.
          example: 21733574
        eans:
          type: array
          description: EAN codes associated with the product.
          items:
            type: string
          example:
            - "3522930003618"
        name:
          type: string
          description: Product name.
          example: Vinotherapist Crème Réparatrice Mains & Ongles - 75 ml
        brand:
          type: string
          description: Product brand name.
          example: Caudalie
        validation_score:
          type: number
          format: int32
          description: |
            CODE | DESCRIPTION
            -----|------------
            -3 | Counterfeit product.
            -2 | Product does not comply with the INCI rules in force in Europe.
            -1 | Product not supported by the application.
            &nbsp;0 | Unknown composition.
            &nbsp;1 | Composition not verified on the product.
            &nbsp;2 | Composition certified by the brand.
            &nbsp;3 | Composition verified on the product.
          example: 3
        score:
          type: number
          format: float
          description: Product rating out of 20.
          example: 11.5
        image:
          type: object
          description: Product photo
          properties:
            image:
              type: string
              format: uri
              description: URL to product photo (The one displayed in the app).
              example: https://incibeauty.com/photos/6/8/e/68ef0a6187430a9c6ef7c2e5648d897e.jpg
            thumbnail:
              type: string
              format: uri
              description: URL to product photo thumbnail.
              example: https://incibeauty.com/photos/thumb/6/8/e/68ef0a6187430a9c6ef7c2e5648d897e.jpg
          required:
            - image
            - thumbnail
        categories:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Category name.
                example: 
              depth:
                type: number
                format: int32
                description: Category depth level starting from 0.
          example:
            - name: Body and face care
              depth: 0
            - name: Hand cream
              depth: 1
        compositions:
          type: object
          properties:
            index:
              type: number
              format: int32
              description: Composition index starting from 1.
              example: 1
            label:
              type: string
              description: Label of the composition when there are several.
            info:
              type: string
              description: Annotations associated with the composition.
              example: "* Ingredients from certified organic agriculture."
            ingredients:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: Internal identifier.
                    example: 19022
                  score:
                    type: number
                    description: |
                      VALUE | DESCRIPTION
                      ------|------------
                      -1 | Unknown ingredient (Grey flower).
                      &nbsp;0 | No penalty (Green flower)
                      &nbsp;2 | Low penalty (Yellow flower)
                      &nbsp;3 | Low penalty (Yellow flower)
                      &nbsp;4 | Medium penalty (Orange flower)
                      &nbsp;5 | Medium penalty (Orange flower)
                      10 | Strong penalty (Red flower)
                    example: 10
                  official_name:
                    type: string
                    description: Ingredient name as listed in the INCI nomenclature.
                    example: SODIUM BORATE
                  additive:
                    type: string
                    description: Code when used as a food additive.
                    example: E285
                  name:
                    type: string
                    description: Localized ingredient name.
                    example: Tétraborate de sodium (Borax)
                  fr_name:
                    type: string
                    deprecated: true
                    description: Use `name` in conjunction with the `Locale` parameter.
                  package_name:
                    type: string
                    description: Ingredient name listed on the product.
                    example: SODIUM BORATE
                  alert:
                    type: string
                    description: Important note associated with the ingredient.
                    example: Banned in cosmetics in Europe from June 12, 2019
                  fr_alert:
                    type: string
                    deprecated: true
                    description: Use `alert` in conjunction with the `Locale` parameter.
                  is_optional:
                    type: boolean
                    description: |
                      `true` The ingredient is part of the [MAY CONTAIN] zone.<br>
                      `false` The ingredient is not part of the [MAY CONTAIN] zone.
                    example: false
                  is_nano:
                    type: boolean
                    description: |
                      `true` The ingredient is present in the form of nanoparticles.<br>
                      `false` The ingredient is not present in the form of nanoparticles.
                    example: false
                  is_active:
                    type: boolean
                    description: |
                      `true` The ingredient is part of the [ACTIVE INGREDIENTS] zone.<br>
                      `false` The ingredient is part of the [INACTIVE INGREDIENTS] zone or if there is no [ACTIVE INGREDIENTS] zone.
                    example: false
                  families:
                    type: array
                    description: List of ingredient families to which the ingredient belongs.
                    items:
                      $ref: '#/components/schemas/IngredientFamily'
                  icons:
                    type: array
                    description: Array of icon URLs associated with the product according to its category or the type of product.
                    items:
                      type: string
                    example:
                      - https://incibeauty.com/img/icon/ic_no_swallow_circle_filled_red@64.png
                required:
                  - id
                  - score
                  - official_name
                  - is_optional
                  - is_nano
                  - is_active

          required:
            - index
            - ingredients
      required:
        - id
        - eans
        - validation_score
        - image
    
    Ingredient:
      type: object
      description: Properties that describe an ingredients.
      properties:
        id:
          type: number
          format: int32
          description: Internal identifier.
          example: 9576
        inci_name:
          type: string
          description: Ingredient name as listed in the INCI nomenclature.
          example: TITANIUM DIOXIDE
        name:
          type: string
          description: Localized ingredient name.
          example: UV filter (Titanium Dioxide)
        description:
          type: string
          description: Description of the ingredient.
          example: "Titanium dioxide is a very abundant mineral on earth..."
        regulation:
          type: string
          description: Rules defined by European regulations concerning the ingredient.
          example: "Maximum permitted concentration as UV filter: 25%..."
        reference:
          type: string
          description: References and sources
          example: "INRS - Fiche toxicologique n°291 - http://www.inrs.fr/..."
        cheminical_iupac_name:
          type: string
          description: Organic compound nomenclature ([More information](https://en.wikipedia.org/wiki/IUPAC_nomenclature_of_organic_chemistry))
        cas:
          type: string
          description: CAS number
          example: 13463-67-7
        einecs_elincs:
          type: string
          description: ELINCS and EINECS number
          example: 236-675-5
        cosmetic_restriction:
          type: string
          description: Annex to the European regulations containing the restrictions concerning the ingredient.
          example: IV/143\nVI/27\nVI/27a (nano)
        score:
          type: number
          description: |
            VALUE | DESCRIPTION
            ------|------------
            &nbsp;0 | No penalty (Green flower)
            &nbsp;2 | Low penalty (Yellow flower)
            &nbsp;3 | Low penalty (Yellow flower)
            &nbsp;4 | Medium penalty (Orange flower)
            &nbsp;5 | Medium penalty (Orange flower)
            10 | Strong penalty (Red flower)
          example: 2
        percentage:
          type: number
          format: float
          description: Percentage of product in which the ingredient is present.
          example: 4.68
        category_percentage:
          type: array
          description: Main product categories in which the ingredient is present.
          items:
            type: object
            properties:
              category_name:
                type: string
                description: Name of the category.
                example: CC Cream
              percentage:
                type: string
                description: Percentage of product in which the ingredient is present.
                example: "55.75"
              count:
                type: number
                format: int32
                description: Number of products in which the ingredient is present.
                example: 194
            required:
              - category_name
              - percentage
              - count
        origin:
          type: array
          description: Information on the origin of the ingredient.
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of ingredient origin.
                example: Mineral
            required:
              - name
        families:
          type: array
          description: List of ingredient families to which the ingredient belongs.
          items:
            $ref: '#/components/schemas/IngredientFamily'
        functions:
          type: array
          description: Information on the function of the ingredient
          items:
            type: object
            properties:
              name:
                type: string
                description: Name of function.
                example: Cosmetic colorant
              description:
                type: string
                description: Description of the function.
                example: Color cosmetics and / or give a color to the skin
            required:
              - name
              - description
        dangers:
          type: array
          description: Colour (score) variation of the ingredient according to the products categories.
          items:
            type: object
            properties:
              value:
                type: number
                description: |
                  VALUE | DESCRIPTION
                  ------|------------
                  &nbsp;0 | No penalty (Green flower)
                  &nbsp;2 | Low penalty (Yellow flower)
                  &nbsp;3 | Low penalty (Yellow flower)
                  &nbsp;4 | Medium penalty (Orange flower)
                  &nbsp;5 | Medium penalty (Orange flower)
                  10 | Strong penalty (Red flower)
                example: 10
              label:
                type: string
                description: Label associated with the value.
                example: "\"Strong penalty\" in the following categories :"
              categories:
                type: array
                description: List of categories associated with an icon (reason for variation).
                items:
                  type: object
                  properties:
                    label:
                      type: string
                      description: Comma-separated list of categories.
                      example: Breath, Children toothpaste, Adult toothpaste, Cream for braces, Children toothbrush, Adult toothbrush, Teeth whitening and stain removal, Solid toothpaste
                    icon:
                      type: string
                      format: uri
                      description: URL to an icon.
                      example: https://incibeauty.com/img/icon/ic_no_swallow_circle_filled_red@64.png
                  required:
                    - label
                    - icon
            required:
              - value
              - label
          example:
            - value: 10
              categories:
                - label: Breath, Children toothpaste, Adult toothpaste, Cream for braces, Children toothbrush, Adult toothbrush, Teeth whitening and stain removal, Solid toothpaste
                  icon: https://incibeauty.com/img/icon/ic_no_swallow_circle_filled_red@64.png
              label: "\"Strong penalty\" in the following categories :"
            - value: 2
              label: "\"Low penalty\" in all other categories."
        special_mentions:
          type: array
          description: List of special mentions, associated with an icon, concerning the ingredient.
          items:
            type: object
            properties:
              label:
                type: string
                description: Special mention.
                example: Penalized in spray products
              icon:
                type: string
                format: uri
                description: URL to an icon.
                example: "https://incibeauty.com/img/icon/ic_spray_circle_filled_red@64.png"
      required:
        - id
        - inci_name
        - score
    
    IngredientFamily:
      type: object
      description: Properties that describe a family of ingredients.
      properties:
        id:
          type: number
          format: int32
          description: Internal identifier.
          example: 17
        name:
          type: string
          description: Family name.
          example: Regulated
        score:
          type: number
          description: |
            VALUE | DESCRIPTION
            ------|------------
            -2 | Unknown (No colour).
            &nbsp;0 | No penalty (Green colour)
            &nbsp;2 | Low penalty (Yellow colour)
            &nbsp;3 | Low penalty (Yellow colour)
            &nbsp;4 | Medium penalty (Orange colour)
            &nbsp;5 | Medium penalty (Orange colour)
            10 | Strong penalty (Red colour)
          example: 2
      required:
        - id
        - name
        - score

